name: The Legacy Project
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9375
  brandStrength: 0
  rhythmicContrast: 0.25
  brandColors:
    - '#020100'
    - '#c6b194'
    - '#302011'
    - '#835b37'
    - '#9d8563'
  lightness: 0
typography_spectrum: 0.90026
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 0
