name: The Legacy Project
favicon: null
layout_spectrum: 0.12356191826984286
typography_spectrum: 0.8283412507735193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9793683225288987
  lightness: 0.9959869016893208
  saturation: 0.6388148437254131
  rhythmicContrast: 0.003955773543566465
purpose: []
