analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0
color:
  saturation: 0.9375
  brandStrength: 0
  rhythmicContrast: 0.25
  brandColors:
    - '#020100'
    - '#c6b194'
    - '#302011'
    - '#835b37'
    - '#9d8563'
  lightness: 0
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: The Legacy Project
typography_spectrum: 0.90026
